### PR TITLE
Changes to Roland Checksum and 14 bit MSB

### PR DESCRIPTION
**Pull request by dnaldoog**
Added a new algorithm for Roland checksums
Fixed MSB 14 bit numbers sending 0xFF instead of 0x7F

### CODE REVIEW

**Comment by damiensellier** [comment]
I just add your mods to the master and 5.6.30 branch.
commit is : https://github.com/RomanKubiak/ctrlr/commit/09f8bc89524d3f8d651a00ed56b6c66b4161c564
Thanks John!

**Comment by dnaldoog** [comment]
Great! Thanks Damien.

**Comment by dnaldoog** [comment]
I am cc`ing this to Tedjuh as well.

I was able to compile vst3 instances of my C-PLG150-AN
<https://sourceforge.net/projects/c-plg150-an/> program using version
5.6.31b. That's great and thank you Damien for all your hard work.

For the first time ever I asked ChatGPT to write a program that replaces
all binary instances of CtrlrX 43 74 72 6C 72 58 with a six string binary
replacement (in my case PLG150 50 4C 47 31 35 30)  Hex to ASCII Text String
Converter <https://www.rapidtables.com/convert/number/hex-to-ascii.html>.

Replacing all (about 300+)  seems to break the vst3 (it isn't recognised in
Reaper on Windows at least) but I found that by replacing 32 strings using
the program, I was able to successfully register the program as
PLG150(CtrlrX) in Reaper! It's probably less than 32 - I tried 3 and it
didn't work. I haven't yet uploaded this file so the the vst3s I uploaded
probably say CtrlrX(CtrlrX)

[image: {659E7C44-1BB2-4F0C-B911-D4405ACA5BFC}.png]

Cubase Pro 13 doesn't show the original or the altered one unfortunately.

Attached is the program ( I *didn't *write) - it's spooky watch chatGPT do
that!

Would be interesting to hear if it works for you. I originally wrote a
program in Ctrlr, but Ctrlr doesn't like loading 32mb files as binary!

[image: {D10EAF31-7A95-4030-A294-1CCA01485A92}.png]

Take care,

John

**Comment by damiensellier** [comment]
Hi John, sorry but I did not understand what you mean about your conversion to string etc
Pictures are missing too.
The mail to discussion feature of github is not really on point.

**Pull request closed without merging**
